name: Push-to-EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy to EC2 on master branch push
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the files
        uses: actions/checkout@v2

      - name: Set up SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.EC2_SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

      - name: Deploy to Server 1
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST_DNS }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          port: 22
          script: |
            # Copy files to the remote server
            rsync -e "ssh -i /home/${{ secrets.USERNAME }}/.ssh/id_rsa -o StrictHostKeyChecking=no" -avz --exclude=excluded_directory/ . ${{ secrets.USERNAME }}@${{ secrets.HOST_DNS }}:${{ secrets.TARGET_DIR }}

            # Execute remote commands
            ssh -i /home/${{ secrets.USERNAME }}/.ssh/id_rsa ${{ secrets.USERNAME }}@${{ secrets.HOST_DNS }} -p 22 "
              sudo apt-get -y update
              sudo apt-get install -y apache2
              sudo systemctl start apache2
              sudo systemctl enable apache2
            "
